# Generated by Django 5.1.1 on 2024-09-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resumes',
        ),
    ]
